name: Building using containerization

on:
  push:
    branches: main
  
jobs:
  container-build-job:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{env.containerRegistry}}/${{env.imageRepository}}:${{github_run_number}}'
        format: 'table'
        severity: 'CRITICAL_HIGH'
        exit-code: '1'
      
        
