name: Getting the source for a git workflow
on:
  push:
    branches:
      -  main
  workflow_dispatch:
jobs:
  source:
    runs-on: ubuntu-latest
    steps:
    -  name: Getting source
       uses: actions/checkout@v3
       with:
         ref: main
         fetch-depth: 1
