name: Building using containerization

on:
  push:
    branches: main
  
jobs:
  container-build-job:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: dotnet build

    - name: Test
      run: dotnet test --no-build --verbosity normal
