name: GloboTicket
on:
  push:
    branches:
      -  main
  workflow_dispatch:
jobs:
  source:
    runs-on: ubuntu-latest
    steps:
    -  name: Getting source
       uses: actions/checkout@v3
        echo "| **Test Name** | **Result**|" >> "$GITHUB_STEP_SUMMARY"
        echo "|--|--|" >> "$GITHUB_STEP_SUMMARY"
        echo "| validate numbers are > 0 |:white_check_mark:|" >> "$GITHUB_STEP_SUMMARY"
        echo "| validate numbers are < 10 |:white_check_mark:|" >> "$GITHUB_STEP_SUMMARY"
        echo "| validate numbers are odd |:x:|" >> "$GITHUB_STEP_SUMMARY"
        echo "| validate numbers are even|:white_check_mark:|" >> "$GITHUB_STEP_SUMMARY"
         
    -  name: Setup .Net
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: 8.0.x

    -  name: Restore
       run: dotnet restore

    -  name: Build
       run: dotnet build --no-restore

    -  name: Test
       run: dotnet test --no-build --verbosity normal
