name: "Chapter8: Compile and Test fast feedback"

on:
  workflow_dispatch:
  push:
    branches: ['feature/*']
    paths:
      -  'fronted/**'
      -  'catalog/**'
      -  'ordering/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -  name: 'Checkout to source'
       uses: actions/checkout@v3

    -  name: 'Setup .Net'
       uses: actions/setup-node@v3
       with:
         dotnet-version: 6.x

    -  name: 'Restore'
       run: dotnet restore

    -  name: 'Build'
       run:  dotnet build --no-restore 
