name: Building & Deply C# Application
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ['windows-latest']
    steps:
      - name: Get the Source
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: '1'
      - name: Setup a .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run:  dotnet build --no-restore
          
      - name: Testing
        run: dotnet test --no-build --verbosity normal
    
